Repository WaitherTeam/Waither-FE, pull requests merged in 2024-04, with the labels that each got.

#34 Fix: 비밀번호 확인 부분 버그 수정
  src/screens/PasswordReset.tsx
Labels: fix

#35 Fix : 회원가입 화면 이메일 입력 버그 수정
  src/screens/Login.tsx
  src/screens/Register.tsx
Labels: fix

#37 Feat: 인삿말 화면 추가
  App.tsx
  ios/Podfile.lock
  src/screens/GreetNaming.tsx
  src/screens/Greeting.tsx
  src/screens/Register.tsx
  tsconfig.json
Labels: feat

#36 Feat: 회원가입 화면KeyboardAwareScrollView 적용
  src/screens/Register.tsx
Labels: bug, fix

#39 Fix: Conflict 해결 - 회원가입완료 버튼, App.tsx에 PasswordReset
  App.tsx
  src/screens/Register.tsx
Labels: fix

#40 Feat: 이름입력 화면 구성, Recoil 설정
  App.tsx
  ios/Podfile.lock
  ios/WAITHER.xcodeproj/project.pbxproj
  package-lock.json
  package.json
  src/recoil/userNameRecoil.js
  src/screens/AskIntro.tsx
  src/screens/GreetNaming.tsx
  src/screens/Greeting.tsx
Labels: feat

#41 Feat: 설문 화면 구성완료, Recoil 적용, asyncStorage 적용
  App.tsx
  ios/Podfile.lock
  package-lock.json
  package.json
  src/assets/images/img-ask1-databox-check.png
  src/assets/images/img-ask1-databox.png
  src/assets/images/img-ask1-databox.svg
  src/recoil/userInitInfoRecoil.tsx
  src/recoil/userNameRecoil.js
  src/screens/AskIntro.tsx
  src/screens/AskNotificationTime.tsx
  src/screens/AskOutro.tsx
  src/screens/AskTimeZone.tsx
  src/screens/AskWeather.tsx
  src/screens/GreetNaming.tsx
  src/screens/Login.tsx
  src/screens/LoginReset.tsx
  src/screens/Register.tsx
Labels: feat

#47 Fix: 시간대 범위 수정 (1~59분), 시간대 변환 로직 수정
  src/screens/AskNotificationTime.tsx
  src/screens/AskTimeZone.tsx
Labels: fix

#49 Feat: Settings, MainScreenSetting, CompanySetting 구현
  App.tsx
  src/assets/images/VectorArrow.png
  src/assets/images/ic-ask-databox.svg
  src/screens/CompanySetting.tsx
  src/screens/Login.tsx
  src/screens/MainScreenSetting.tsx
  src/screens/Register.tsx
  src/screens/Settings.tsx
Labels: feat

#48 Feat: SettingWind 화면 구성, recoil 구성
  App.tsx
  ios/Podfile.lock
  package-lock.json
  package.json
  src/assets/images/wind_group.svg
  src/assets/images/wind_power.svg
  src/recoil/userDataRecoil.tsx
  src/recoil/waitherDataRecoil.tsx
  src/screens/Login.tsx
  src/screens/SettingWind.tsx
Labels: feat

#50 Feat: PrivacySetting 설정 완료, recoil 설정 완료
  App.tsx
  src/recoil/userInitInfoRecoil.tsx
  src/screens/PrivacySetting.tsx
  src/screens/Settings.tsx
Labels: feat

#53 Fix: 임시 비밀번호 발급 멘트 수정
  src/screens/LoginReset.tsx
Labels: fix
